import path from 'node:path';

function ensureObject(value, label) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${label} must be an object.`);
  }
}

export function parsePackageFixture(raw) {
  ensureObject(raw, 'fixture');
  const { package: pkg, tap } = raw;
  ensureObject(pkg, 'fixture.package');

  if (!pkg.name || !pkg.version || !pkg.description || !pkg.license) {
    throw new Error('fixture.package requires name, version, description, and license.');
  }

  const slug = pkg.name.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase();
  const homepage = pkg.homepage ?? `https://example.com/${slug}`;
  const repository = pkg.repository ?? homepage;
  const owner = tap?.owner ?? 'acme';
  const repo = tap?.repo ?? `homebrew-${slug}`;
  const formulaClass = slug
    .split('-')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');

  return {
    slug,
    formulaName: slug,
    formulaClass,
    packageName: pkg.name,
    version: pkg.version,
    description: pkg.description,
    license: pkg.license,
    homepage,
    repository,
    owner,
    repo,
    binaries: Array.isArray(pkg.binaries) && pkg.binaries.length > 0 ? pkg.binaries : [slug],
    install: pkg.install ?? {},
    caveats: pkg.caveats ?? [],
    test: pkg.test ?? { command: `${slug} --help`, expect: 'Usage' },
    artifacts: raw.artifacts ?? []
  };
}

export function renderFormula(spec) {
  const caveatBlock = spec.caveats.length
    ? `\n  def caveats\n    <<~EOS\n${spec.caveats.map((line) => `      ${line}`).join('\n')}\n    EOS\n  end\n`
    : '';

  const installLines = spec.binaries.map((bin) => `    bin.install "dist/${bin}"`).join('\n');
  const command = spec.test.command.trim();
  const separator = command.search(/\s/);
  const executable = separator === -1 ? command : command.slice(0, separator);
  const argumentsText = separator === -1 ? '' : command.slice(separator);
  if (!spec.binaries.includes(executable)) {
    throw new Error(`fixture.package.test.command must start with a declared binary: ${spec.binaries.join(', ')}.`);
  }
  const testCommand = `#{bin}/${executable}${argumentsText.replaceAll('#{', '\\#{')}`;

  return `class ${spec.formulaClass} < Formula\n  desc ${JSON.stringify(spec.description)}\n  homepage ${JSON.stringify(spec.homepage)}\n  url ${JSON.stringify(`${spec.repository}/archive/refs/tags/v${spec.version}.tar.gz`)}\n  sha256 ${JSON.stringify('REPLACE_WITH_SHA256')}\n  license ${JSON.stringify(spec.license)}\n\n  def install\n${installLines}\n  end\n\n  test do\n    output = shell_output(${JSON.stringify(testCommand)})\n    assert_match ${JSON.stringify(spec.test.expect)}, output\n  end${caveatBlock}end\n`;
}

export function renderTapReadme(spec) {
  return `# homebrew-${spec.repo.replace(/^homebrew-/, '')}

Generated by brewpack for **${spec.packageName}**.

## Install

\`\`\`sh
brew tap ${spec.owner}/${spec.repo}
brew install ${spec.formulaName}
\`\`\`

## Update checklist

1. Build release artifacts locally.
2. Upload them to a GitHub release for \`v${spec.version}\`.
3. Replace the formula SHA256 after downloading the tarball.
4. Run \`brewpack validate .\` from the tap repo root.

## Safety

- No hidden network calls are made by brewpack.
- Publishing is always manual and documented.
- Review generated formula paths before committing.
`;
}


export function buildPlan(spec) {
  return {
    packageName: spec.packageName,
    formulaName: spec.formulaName,
    formulaClass: spec.formulaClass,
    tapRepository: `${spec.owner}/${spec.repo}`,
    releaseArchiveUrl: `${spec.repository}/archive/refs/tags/v${spec.version}.tar.gz`,
    binaries: spec.binaries,
    caveats: spec.caveats,
    nextSteps: [
      'Build release artifacts into dist/.',
      'Generate or verify the GitHub release tarball hash.',
      'Commit generated Formula and README files to the tap repository.'
    ]
  };
}

export function validateTapLayout(files) {
  const required = ['Formula', 'README.md'];
  const missing = required.filter((item) => !files.includes(item));
  return {
    valid: missing.length === 0,
    missing
  };
}

export function resolveOutputPaths(outputDir, spec) {
  return {
    root: outputDir,
    formulaDir: path.join(outputDir, 'Formula'),
    formulaFile: path.join(outputDir, 'Formula', `${spec.formulaName}.rb`),
    readmeFile: path.join(outputDir, 'README.md'),
    planFile: path.join(outputDir, 'brewpack.plan.json')
  };
}
