import path from 'node:path';

function ensureObject(value, label) {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`${label} must be an object.`);
  }
}

function parseArtifact(raw, binaries) {
  if (!Array.isArray(raw.artifacts) || raw.artifacts.length !== 1) {
    throw new Error('fixture.artifacts must contain exactly one release artifact.');
  }
  const artifact = raw.artifacts[0];
  ensureObject(artifact, 'fixture.artifacts[0]');
  ensureObject(artifact.install, 'fixture.artifacts[0].install');
  if (typeof artifact.url !== 'string' || !/^https?:\/\/\S+$/.test(artifact.url)) {
    throw new Error('fixture.artifacts[0].url must be an absolute HTTP(S) URL.');
  }

  const declared = Object.keys(artifact.install);
  const missing = binaries.filter((binary) => !declared.includes(binary));
  const unknown = declared.filter((binary) => !binaries.includes(binary));
  if (missing.length || unknown.length) {
    const details = [
      missing.length ? `missing install paths for: ${missing.join(', ')}` : '',
      unknown.length ? `undeclared binaries: ${unknown.join(', ')}` : ''
    ].filter(Boolean).join('; ');
    throw new Error(`fixture.artifacts[0].install must match fixture.package.binaries (${details}).`);
  }

  for (const [binary, source] of Object.entries(artifact.install)) {
    if (
      typeof source !== 'string'
      || !source
      || path.isAbsolute(source)
      || source.split(/[\\/]/).includes('..')
    ) {
      throw new Error(`fixture.artifacts[0].install.${binary} must be a relative path inside the artifact.`);
    }
  }
  return { url: artifact.url, install: artifact.install };
}

export function parsePackageFixture(raw) {
  ensureObject(raw, 'fixture');
  const { package: pkg, tap } = raw;
  ensureObject(pkg, 'fixture.package');

  if (!pkg.name || !pkg.version || !pkg.description || !pkg.license) {
    throw new Error('fixture.package requires name, version, description, and license.');
  }

  const slug = pkg.name.replace(/[^a-zA-Z0-9]+/g, '-').replace(/^-|-$/g, '').toLowerCase();
  const homepage = pkg.homepage ?? `https://example.com/${slug}`;
  const repository = pkg.repository ?? homepage;
  const owner = tap?.owner ?? 'acme';
  const repo = tap?.repo ?? `homebrew-${slug}`;
  const camelizedSlug = slug
    .split('-')
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('');
  const formulaClass = /^\d/.test(camelizedSlug) ? `V${camelizedSlug}` : camelizedSlug;

  const binaries = Array.isArray(pkg.binaries) && pkg.binaries.length > 0 ? pkg.binaries : [slug];
  const artifact = parseArtifact(raw, binaries);
  return {
    slug,
    formulaName: slug,
    formulaClass,
    packageName: pkg.name,
    version: pkg.version,
    description: pkg.description,
    license: pkg.license,
    homepage,
    repository,
    owner,
    repo,
    binaries,
    install: pkg.install ?? {},
    caveats: pkg.caveats ?? [],
    test: pkg.test ?? { command: `${slug} --help`, expect: 'Usage' },
    artifact
  };
}

export function renderFormula(spec) {
  const caveatBlock = spec.caveats.length
    ? `\n  def caveats\n    <<~EOS\n${spec.caveats.map((line) => `      ${line}`).join('\n')}\n    EOS\n  end\n`
    : '';

  const installLines = spec.binaries
    .map((bin) => {
      const source = spec.artifact.install[bin];
      const sourceBasename = path.posix.basename(source.replaceAll('\\', '/'));
      const destination = sourceBasename === bin ? '' : ` => ${JSON.stringify(bin)}`;
      return `    bin.install ${JSON.stringify(source)}${destination}`;
    })
    .join('\n');
  const command = spec.test.command.trim();
  const separator = command.search(/\s/);
  const executable = separator === -1 ? command : command.slice(0, separator);
  const argumentsText = separator === -1 ? '' : command.slice(separator);
  if (!spec.binaries.includes(executable)) {
    throw new Error(`fixture.package.test.command must start with a declared binary: ${spec.binaries.join(', ')}.`);
  }
  const testCommand = `#{bin}/${executable}${argumentsText.replaceAll('#{', '\\#{')}`;

  return `class ${spec.formulaClass} < Formula\n  desc ${JSON.stringify(spec.description)}\n  homepage ${JSON.stringify(spec.homepage)}\n  url ${JSON.stringify(spec.artifact.url)}\n  sha256 ${JSON.stringify('REPLACE_WITH_SHA256')}\n  license ${JSON.stringify(spec.license)}\n\n  def install\n${installLines}\n  end\n\n  test do\n    output = shell_output(${JSON.stringify(testCommand)})\n    assert_match ${JSON.stringify(spec.test.expect)}, output\n  end${caveatBlock || '\n'}end\n`;
}

export function renderTapReadme(spec) {
  return `# homebrew-${spec.repo.replace(/^homebrew-/, '')}

Generated by brewpack for **${spec.packageName}**.

## Install

\`\`\`sh
brew tap ${spec.owner}/${spec.repo}
brew install ${spec.formulaName}
\`\`\`

## Update checklist

1. Build the release artifact containing: ${Object.values(spec.artifact.install).map((item) => `\`${item}\``).join(', ')}.
2. Upload it to \`${spec.artifact.url}\`.
3. Download that exact URL and replace the formula SHA256 with its checksum.
4. Run \`brewpack validate .\` from the tap repo root.

## Safety

- No hidden network calls are made by brewpack.
- Publishing is always manual and documented.
- Review generated formula paths before committing.
`;
}


export function buildPlan(spec) {
  return {
    packageName: spec.packageName,
    formulaName: spec.formulaName,
    formulaClass: spec.formulaClass,
    tapRepository: `${spec.owner}/${spec.repo}`,
    releaseArchiveUrl: spec.artifact.url,
    artifactInstall: spec.artifact.install,
    binaries: spec.binaries,
    caveats: spec.caveats,
    generatedFiles: [
      `Formula/${spec.formulaName}.rb`,
      'README.md',
      'brewpack.plan.json'
    ],
    nextSteps: [
      `Build the release artifact with: ${Object.values(spec.artifact.install).join(', ')}.`,
      `Download ${spec.artifact.url} and generate its SHA256.`,
      'Commit generated Formula and README files to the tap repository.'
    ]
  };
}

export function validateTapLayout(files) {
  const required = ['Formula', 'README.md'];
  const missing = required.filter((item) => !files.includes(item));
  return {
    valid: missing.length === 0,
    missing
  };
}

export function resolveOutputPaths(outputDir, spec) {
  return {
    root: outputDir,
    formulaDir: path.join(outputDir, 'Formula'),
    formulaFile: path.join(outputDir, 'Formula', `${spec.formulaName}.rb`),
    readmeFile: path.join(outputDir, 'README.md'),
    planFile: path.join(outputDir, 'brewpack.plan.json')
  };
}
